/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controlador.Controller;
import javax.swing.JOptionPane;
import model.bean.Conta;
import model.dao.ContaDAO;

/**
 *
 * @author anton
 */
public class telaUsuario extends javax.swing.JFrame {

    Controller c = new Controller();

    /**
     * Creates new form telaUsuario
     */
    public telaUsuario() {
        initComponents();
        meuID();
    }

    public void meuID() {
        ContaDAO cDao = new ContaDAO();

        for (Conta c : cDao.readForLogin(System.getProperty("loginUsuarioDoBD"))) {

            jLabelID.setText(String.valueOf(c.getIdContas()));
            break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSaque = new javax.swing.JButton();
        jButtonSaldo = new javax.swing.JButton();
        jButtonTransferencia = new javax.swing.JButton();
        jButtonDeposito = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem vindo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 632, 38));

        jButtonSaque.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSaque.setText("Efetuar Saque");
        jButtonSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaqueActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 185, 44));

        jButtonSaldo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSaldo.setText("Verificar Saldo");
        jButtonSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaldoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 185, 44));

        jButtonTransferencia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonTransferencia.setText("Efetuar Transferência");
        jButtonTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferenciaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 44));

        jButtonDeposito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonDeposito.setText("Efetuar Deposito");
        jButtonDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 185, 44));

        jButtonSair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 109, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Seu ID é:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, 30));

        jLabelID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelID.setText("jLabel3");
        jPanel1.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaqueActionPerformed
        // TODO add your handling code here:
        ContaDAO cDao = new ContaDAO();

        String salvarRetorno;
        String quantidade = JOptionPane.showInputDialog(null, "Digite o valor de dinheiro que deseja Sacar");

        for (Conta c : cDao.readForLogin(System.getProperty("loginUsuarioDoBD"))) {
            salvarRetorno = c.sacar(Double.parseDouble(quantidade));

            if (salvarRetorno.equals("Sucesso")) {

                JOptionPane.showMessageDialog(this, "Depósito realizado com sucesso!");

            } else {
                JOptionPane.showMessageDialog(this, "Deposito de valor inferior a R$ 0");
                return;
            }
            break;
        }
    }//GEN-LAST:event_jButtonSaqueActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        c.executarTelaInicial();
        dispose();

    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaldoActionPerformed
        // TODO add your handling code here:
        ContaDAO cDao = new ContaDAO();

        for (Conta c : cDao.readForLogin(System.getProperty("loginUsuarioDoBD"))) {
//            cDao.update(c);
            JOptionPane.showMessageDialog(null, "Seu saldo é R$ " + c.saldo());
            break;
        }

    }//GEN-LAST:event_jButtonSaldoActionPerformed

    private void jButtonDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositoActionPerformed
        // TODO add your handling code here:
        ContaDAO cDao = new ContaDAO();

        String quantidade = JOptionPane.showInputDialog(null, "Digite a quantidade de dinheiro deseja depositar");

        for (Conta c : cDao.readForLogin(System.getProperty("loginUsuarioDoBD"))) {

            if (c.depositar(Double.parseDouble(quantidade)) == true) {
//                cDao.update(c);
                JOptionPane.showMessageDialog(this, "Deposito realizado com sucesso!");
                break;
            } else {

                JOptionPane.showMessageDialog(this, "Erro ao realizar o deposito");
            }
        }


    }//GEN-LAST:event_jButtonDepositoActionPerformed

    private void jButtonTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferenciaActionPerformed
        // TODO add your handling code here:
        c.executarTelaTransferencia();
        dispose();
    }//GEN-LAST:event_jButtonTransferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeposito;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSaldo;
    private javax.swing.JButton jButtonSaque;
    private javax.swing.JButton jButtonTransferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
